language: node_js
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt build
env:
  matrix:
    secure: VcGL2NGettR3TvbxeP2R0qrCuKEsmUuFw+ZceQHQIOug8L1szpX3D1mVjjYNvGcjWpc1l6RRNP33+LDPNXcXN3F+P2jX5c/KFzq9zDso9HiAMCua6oFhrbgxR0IZgJc2EK5e//FDd68vZuSn1oPTbfVJd9tJ586pzYPBl2oSvq5dPOv4GK7s8ZSmn3P1tFRAOC6r3E4sNDxCtw7GZv8NpsaZ2qw5zKzzs3jMRGDwej0UDbOeo7HlQcUJmPZYEL2SV21+zV0C+RIzNA42iO4YSh4UnCIbdtunTlna+BI4k5g1A/8rlI+fn1u344G3dnhPFDCChvP+pZKdtbYp6YutFrF5CY7AHepriKCgiWiZIIk7sQFD5z50+B9UdK7MvwaMIn8RFesOc0GR1GxaEWmvRhO9dsYI5uesKdbWd+07YYyErlYaTKrbNa80X9YaTpb7Lu+8F+pAUkOiF/TRUEj+e4zBcBDUEvmppARf5MhI3/hmtP8HDR0RPkOZZ7Jlyg031bgbaX9oMd7Ghq2cu52cIbbuDrMgBNzdMEMvqksXMurgxbT27gbXpvEYke3drFtAwqDUZ+TVTsVBkqP4EC0vhtxiZe+6UqIpSNephaNev/QdRjc8U9VvQR/NWAWw3BOgdw1LIENEq9P6W6mdtomH7RgnwUO9yyl3EFwo4IiaUIM=
